export const dataCategoryItemTypes = {

  ADD_CATEGORY: "ADD_CATEGORY",
  ADD_ITEM: "ADD_ITEM",
  UPDATE_CATEGORY_ITEM: "UPDATE_CATEGORY_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_CATEGORY_ITEM: "DELETE_CATEGORY_ITEM",
  DELETE_ITEM: "DELETE_ITEM"
}